CREATE TABLE FOLLOWER (ID INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN_KEY(TYPE_ID) REFERENCES FOLLOWERTYPE(ID));
CREATE TABLE FOLLOWERTYPE (ID INTEGER PRIMARY KEY AUTOINCREMENT, TYPE_ID INTEGER NOT NULL, IMAGE_PATH TEXT NOT NULL);
