CREATE TABLE FOLLOWERTYPE (ID INTEGER PRIMARY KEY AUTOINCREMENT, IMAGE_PATH TEXT NOT NULL);
CREATE TABLE FOLLOWER (TYPE_ID INTEGER, FOREIGN KEY(TYPE_ID) REFERENCES FOLLOWERTYPE(ID));
CREATE TABLE PLAYERSTATE (ID INTEGER PRIMARY KEY, LEVEL INTEGER, REPUTATION INTEGER, LEVEL_UP_THRESHOLD, MAX_LEVEL INTEGER);

INSERT INTO FOLLOWERTYPE VALUES (1, 'sprites//Meep//Gossiper//');
INSERT INTO FOLLOWERTYPE VALUES (2, 'sprites//Meep//Promoter//');
INSERT INTO FOLLOWERTYPE VALUES (3, 'sprites//Meep//Deceiver//');

INSERT INTO FOLLOWER VALUES (1);
INSERT INTO FOLLOWER VALUES (1);
INSERT INTO FOLLOWER VALUES (2);
INSERT INTO FOLLOWER VALUES (3);

INSERT INTO PLAYERSTATE VALUES (1, 0, 1000, 1000, 5);
