CREATE TABLE USER (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, ACCOUNT_IDENTIFIER TEXT NOT NULL, STATE INT NOT NULL, ALIAS TEXT);
CREATE TABLE USER_INFO (ID INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY(USER_ID) REFERENCES USER(ID), REPUTATION INT NOT NULL, VOTES INT NOT NULL);
CREATE TABLE STRATEGY (ID INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY(USER_ID) REFERENCES USER(ID), TYPE INT NOT NULL);
CREATE TABLE EXPRESSION (ID INTEGER PRIMARY KEY AUTOINCREMENT, TYPE INT NOT NULL);
